name: Android Release (no EAS)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      CI: "false"           # tránh Metro coi là CI gây treo
      EXPO_NO_TELEMETRY: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Android SDK
        uses: android-actions/setup-android@v3

      - name: Install deps (npm install)
        run: npm install --no-audit --no-fund

      - name: Prebuild Android (Expo Managed -> bare android/)
        run: npx expo prebuild -p android --no-install

      # FIX: Bump Kotlin to 1.9.25 to match Compose Compiler 1.5.15
      - name: Force Kotlin 1.9.25 (Compose compatibility)
        run: |
          FILE="android/gradle/libs.versions.toml"
          if [ -f "$FILE" ]; then
            cp "$FILE" "$FILE.bak"
            # cập nhật cả alias plugin nếu có
            perl -0777 -pe 's/kotlin\s*=\s*"(1\.9\.2[0-9])"/kotlin = "1.9.25"/g' "$FILE" > tmp.toml || true
            perl -0777 -pe 's/jetbrains-kotlin-android\s*=\s*"(1\.9\.2[0-9])"/jetbrains-kotlin-android = "1.9.25"/g' tmp.toml > tmp2.toml || true
            mv tmp2.toml "$FILE"
            echo "Kotlin version after patch:"
            grep -E 'kotlin\s*=|jetbrains-kotlin-android' "$FILE" || true
          else
            echo "versions.toml not found; skipping kotlin bump."
          fi

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      # Patch signing: dùng debug keystore cho release để cài lên máy test (không dành cho Play Store)
      - name: Use debug signing for release
        run: |
          APP_BUILD_GRADLE="android/app/build.gradle"
          cp "$APP_BUILD_GRADLE" "$APP_BUILD_GRADLE.bak"
          # Thay signingConfig của release = signingConfigs.debug
          perl -0777 -pe "s/release\s*\{([^}]*)signingConfig\s+signingConfigs\.release([^}]*)\}/release {\\1signingConfig signingConfigs.debug\\2}/s" "$APP_BUILD_GRADLE" > tmp.gradle || true
          # Nếu không có release signing, thì chèn vào bên trong buildTypes.release
          if ! grep -q "signingConfig signingConfigs.debug" tmp.gradle; then
            perl -0777 -pe "s/buildTypes\s*\{\s*release\s*\{([^}]*)\}/buildTypes { release {\\1\n        signingConfig signingConfigs.debug\n    }}/s" "$APP_BUILD_GRADLE" > tmp2.gradle || true
            mv tmp2.gradle tmp.gradle
          fi
          mv tmp.gradle "$APP_BUILD_GRADLE"
          echo "Patched release signing to use debug keystore."

      - name: Build APK (release)
        working-directory: android
        run: ./gradlew :app:assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
