name: Android Release (no EAS)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      CI: "false"
      EXPO_NO_TELEMETRY: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Android SDK
        uses: android-actions/setup-android@v3

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Prebuild Android
        run: npx expo prebuild -p android --no-install

      # Force Kotlin 1.9.25 everywhere
      - name: Force Kotlin 1.9.25
        run: |
          echo "kotlinVersion=1.9.25" >> android/gradle.properties
          echo "android.kotlinVersion=1.9.25" >> android/gradle.properties
          echo ">>> gradle.properties content:"
          cat android/gradle.properties

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Use debug signing for release
        run: |
          APP_BUILD_GRADLE="android/app/build.gradle"
          cp "$APP_BUILD_GRADLE" "$APP_BUILD_GRADLE.bak" || true
          perl -0777 -pe "s/release\s*\{([^}]*)signingConfig\s+signingConfigs\.release([^}]*)\}/release {\\1signingConfig signingConfigs.debug\\2}/s" "$APP_BUILD_GRADLE" > tmp.gradle || true
          if ! grep -q "signingConfig signingConfigs.debug" tmp.gradle; then
            perl -0777 -pe "s/buildTypes\s*\{\s*release\s*\{([^}]*)\}/buildTypes { release {\\1\n        signingConfig signingConfigs.debug\n    }}/s" "$APP_BUILD_GRADLE" > tmp2.gradle || true
            mv tmp2.gradle tmp.gradle
          fi
          mv tmp.gradle "$APP_BUILD_GRADLE"

      - name: Build APK (release)
        working-directory: android
        run: ./gradlew -Pandroid.kotlinVersion=1.9.25 -Pkotlin.version=1.9.25 :app:assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
